### ISSUE TITLE
First release TODO

### ISSUE THREAD

**Issue by knuxify** [punctum-im/drywall#2]
This issue serves as a list of tasks that will have to be done before the first release.

## API

 - [ ] Standardize, implement and document server<->client communications with websockets (standardized in the rewrite)
 - [ ] Implement federation (may require some changes to the protocol)
 - [ ] Missing endpoints:
    * [ ] ``/api/v1/accounts\invites/by-name`` endpoints
    * [ ] Search endpoints

## Authentication
 - [ ] Standardize, implement and document authentication (currently looking at OAuth2 with authlib) (#7)
    * Client settings (web interface)
    * Auth tokens for API access
    * New web interface for auth management
 - Write tests

## Tests
 - [x] API (2ae65a9ed3beac350e8788168e394e881266c326)
    * [X] ~~They're terrible. Rewrite, or split up.~~ Rewritten! (02f1ea90c35bb738aa79fb922a107c41954d0e4f)
    * [X] Add more fail cases (Crossing this one off for the sake of focusing on other things)
 - [x] Objects (036d654d9c04434cf388b5e5991c9af2fd9d3e6d)
    * [X] Add fail cases to get 100% coverage on objects (c7991f5d5a558a1fb3c187d3f3436c9893def353)
 - [X] Database (96e24a89658c85c686a9e9fc9a1ce802143f0630)
    * [ ] Clean up, add fail cases
 - [X] Look into pytest (5da52786e8cdd9a8ff65944b5dd13ac200f01bca, 2ae65a9ed3beac350e8788168e394e881266c326)
 - [X] Add code coverage checks (826ca4e330b1c5991d1af9bcba42f851c670c890)
 - [ ] Web interface
 - Auth, see Auth section

## Documentation
 - [X] Setup for development (6757d4df66fffc75d344c6a17ff00c0645961487)
 - [ ] Setup for production
 - [x] API response documentation
 - [ ] Development documentation

## Meta, code quality

- [ ] Add .flake8 file with default flake8 config
- [ ] Add GitHub issue templates (and GitLab issue templates, if we move there)
- [ ] Replace error pings; clean up error handling?

## Web

 - [ ] Admin UI, update config when instance object is edited
 - [ ] Instance about page
 - [ ] Design refresh / general project-wide brand identity

## Missing features
 - [ ] Implement user deletion; my idea is, we give a 15-day time where the account isn't fully deleted, just nulled out (so that we can recover it for example when a hacker removes the account) then redirect all messages with this uses set as an owner to a stub object
 - [ ] Proper username validation (#7)

## For future consideration
 - Some kind of file attachment API, since we don't want to force users to use external CDNs. Overall client support will probably need a huge protocol update of its own.

---

# Old, finished tasks

## Database backends
 - ~~Dummy~~
 - ~~SQLite3 (2ab4dae943ae8c7cf670e72c48b7a9810bcd1d1f)~~
 - [X] SQLAlchemy (replacement for the above 2) (#6)

## Objects
 - [X] Add new variable for keys that take IDs, so that it can be used in a function that checks if these IDs exist (things like quoted message IDs or conference user roles) (87e37e616408b19a6f1a89c8aa6582f56425e823, still needs to handle lists)

## Others
 - [x] Implement all existing API methods (as of PR2) (81fa2ce8d3167ed07fc4b941e888d01c1070f0f9, except for ones that require authentication)
 - [X] Get id_lists working in init_object (0b0afbcb7e8beaf7ac7008c93074310a7e3e3972)
 - [X] Properly handle dates (7b3655e992a35b6e58b6384eb69eebd906629157 and some extras)
 - [X] Add unique key value for object classes to prevent multiple accounts/invites with the same name from being created (0e02770f38c5249bbf95a228e262646ed322f357)
 - [x] Fix error handling in __patch_object and __post_object functions
 - [x] Report function (make reports objects for easier federation?) (f6d1280467891a60880748c1943b7bfb6af53ff2)
 - [X] e-mail validation in forms(?) (e98bae4494c756840f42aa63019bb44e965ec83f)
